version: "3.8"

services:

  db:
    image: "postgres:14-alpine"
    container_name: boilerplate-db
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2021
      - POSTGRES_DB=boilerplate

  db-test:
    image: "postgres:14-alpine"
    container_name: boilerplate-db-test
    restart: on-failure
    ports:
      - "6432:6432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2021
      - POSTGRES_DB=boilerplate-test
