version: "3.8"

services:

  db:
    image: "postgres:14-alpine"
    container_name: boilerplate-db
    restart: on-failure
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TheAnswerIsPosgres42!
      - POSTGRES_DB=boilerplate

  db-test:
    image: "postgres:14-alpine"
    container_name: boilerplate-db-test
    restart: on-failure
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TheAnswerIsPosgres42!
      - POSTGRES_DB=boilerplate-test
